server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_touth
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
          - Path=/payment/get/**
          - After=2020-03-27T13:56:31.377+08:00[Asia/Shanghai]
#          - Cookie=nameuser,lizs

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


